spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${DB_IP}:3306/${DB_NAME}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: SPHHikariPool
  flyway:
    out-of-order: true
    baseline-version: 1
    baseline-on-migrate: true
    url: jdbc:mysql://${DB_IP}:3306/${DB_NAME}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration

#10:05mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: flag # 全局逻辑删除的实体字段名(配置后可以忽略不配置步骤二)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(配置后可以忽略不配置步骤二)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
mes:
  database:
    origins:
      suzhou:
        url: ${MES_DATABASE_SUZHOU_URL:jdbc:mysql://11.11.11.13:3306/mo_mes_db}
        username: ${MES_DATABASE_SUZHOU_USERNAME:root}
        password: ${MES_DATABASE_SUZHOU_PASSWORD:momeshou}
      mianyang:
        url: ${MES_DATABASE_MIANYANG_URL:jdbc:mysql://192.168.188.11:3306/mo_mes_db}
        username: ${MES_DATABASE_MIANYANG_USERNAME:root}
        password: ${MES_DATABASE_MIANYANG_PASSWORD:momeshou}

