CREATE TABLE IF NOT EXISTS  `mo_produce_order` (
  `id` int NOT NULL AUTO_INCREMENT,
  `work_order_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '工单编号',
  `order_date` date DEFAULT NULL COMMENT '单据日期',
  `material_code` varchar(16) DEFAULT NULL COMMENT '物料编号',
  `material_name` varchar(256) DEFAULT NULL COMMENT '物料名称',
  `model_type` varchar(64) DEFAULT NULL COMMENT '规格型号',
  `workshop` varchar(32) DEFAULT NULL COMMENT '生产车间',
  `produce_count` int DEFAULT NULL COMMENT '计划生产数量',
  `produce_unit` varchar(16) DEFAULT NULL COMMENT '产品单位',
  `planned_starttime` datetime DEFAULT NULL COMMENT '计划开工时间',
  `planned_endtime` datetime DEFAULT NULL COMMENT '计划完工时间',
  `added_time` datetime DEFAULT NULL,
  `flow_code` varchar(32) DEFAULT NULL COMMENT '工艺流程编号',
  `flow_assemble_shell` int DEFAULT '0',
  `bom_version` varchar(32) DEFAULT NULL COMMENT 'BOM版本',
  `schedule_state` varchar(16) DEFAULT NULL COMMENT '排产状态',
  `cmos_pn` varchar(32) DEFAULT NULL COMMENT 'CMOS批号',
  `lens_sn` varchar(32) DEFAULT NULL COMMENT '镜头批号',
  `fpga_version` varchar(32) DEFAULT NULL COMMENT 'FPGA版本号',
  `order_state` int DEFAULT '0' COMMENT '工单状态',
  `completed_count` int DEFAULT '0',
  `product_type` varchar(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `aq_` (`work_order_code`,`order_date`,`material_code`,`produce_count`)
) ENGINE=InnoDB AUTO_INCREMENT=363 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='生产工单信息表';