ALTER TABLE `mo_beam_appearance_inspection`
MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
MODIFY COLUMN `aa_hole_diameter` decimal(10,4) DEFAULT NULL COMMENT 'AA孔直径',
MODIFY COLUMN `aa_hole_distance` decimal(10,4) DEFAULT NULL COMMENT 'AA孔孔距',
MODIFY COLUMN `aa_hole_center_x` decimal(10,4) DEFAULT NULL COMMENT 'AA孔中心X值',
MODIFY COLUMN `aa_hole_center_y` decimal(10,4) DEFAULT NULL COMMENT 'AA孔中心Y值',
MODIFY COLUMN `thread_hole_distance` decimal(10,4) DEFAULT NULL COMMENT '螺纹孔孔距',
MODIFY COLUMN `thread_hole_center_x` decimal(10,4) DEFAULT NULL COMMENT '螺纹孔中心X值',
MODIFY COLUMN `thread_hole_center_y` decimal(10,4) DEFAULT NULL COMMENT '螺纹孔中心Y值',
MODIFY COLUMN `surface_height_diff` decimal(10,4) DEFAULT NULL COMMENT '贴合面高度差',
MODIFY COLUMN `surface_to_beam_diff` decimal(10,4) DEFAULT NULL COMMENT '贴合面与横梁差值',
MODIFY COLUMN `beam_length` decimal(10,4) DEFAULT NULL COMMENT '横梁长度',
MODIFY COLUMN `beam_width` decimal(10,4) DEFAULT NULL COMMENT '横梁宽度',
MODIFY COLUMN `mo_process_step_production_result_id` bigint DEFAULT NULL COMMENT '生产结果ID',
MODIFY COLUMN `error_code` int DEFAULT NULL COMMENT '错误代码',
MODIFY COLUMN `station_num` int DEFAULT NULL COMMENT '工位编号',
MODIFY COLUMN `ng_reason` varchar(100) DEFAULT NULL COMMENT '不良原因',
MODIFY COLUMN `add_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
MODIFY COLUMN `beam_sn` varchar(255) DEFAULT NULL COMMENT '横梁序列号',
MODIFY COLUMN `position` varchar(255) DEFAULT NULL COMMENT '位置',
MODIFY COLUMN `aa_hole_diameter_usl` decimal(10,4) DEFAULT NULL COMMENT 'AA孔直径上限',
MODIFY COLUMN `aa_hole_diameter_lsl` decimal(10,4) DEFAULT NULL COMMENT 'AA孔直径下限',
MODIFY COLUMN `aa_hole_distance_usl` decimal(10,4) DEFAULT NULL COMMENT 'AA孔孔距上限',
MODIFY COLUMN `aa_hole_distance_lsl` decimal(10,4) DEFAULT NULL COMMENT 'AA孔孔距下限',
MODIFY COLUMN `thread_hole_distance_usl` decimal(10,4) DEFAULT NULL COMMENT '螺纹孔孔距上限',
MODIFY COLUMN `thread_hole_distance_lsl` decimal(10,4) DEFAULT NULL COMMENT '螺纹孔孔距下限',
MODIFY COLUMN `bonding_surface_height_diff_usl` decimal(10,4) DEFAULT NULL COMMENT '贴合面高度差上限',
MODIFY COLUMN `bonding_surface_to_beam_diff_usl` decimal(10,4) DEFAULT NULL COMMENT '贴合面与横梁差值上限',
MODIFY COLUMN `beam_length_usl` decimal(10,4) DEFAULT NULL COMMENT '横梁长度上限',
MODIFY COLUMN `beam_length_lsl` decimal(10,4) DEFAULT NULL COMMENT '横梁长度下限',
MODIFY COLUMN `beam_width_usl` decimal(10,4) DEFAULT NULL COMMENT '横梁宽度上限',
MODIFY COLUMN `beam_width_lsl` decimal(10,4) DEFAULT NULL COMMENT '横梁宽度下限';

ALTER TABLE `mo_laser_marking_inspection`
MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
MODIFY COLUMN `laser_power` float DEFAULT NULL COMMENT '激光功率',
MODIFY COLUMN `laser_template_no` varchar(255) DEFAULT NULL COMMENT '激光模板编号',
MODIFY COLUMN `mo_process_step_production_result_id` bigint DEFAULT NULL COMMENT '生产结果ID',
MODIFY COLUMN `error_code` int DEFAULT NULL COMMENT '错误代码',
MODIFY COLUMN `station_num` int DEFAULT NULL COMMENT '工位编号',
MODIFY COLUMN `ng_reason` varchar(100) DEFAULT NULL COMMENT '不良原因',
MODIFY COLUMN `add_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
MODIFY COLUMN `beam_sn` varchar(255) DEFAULT NULL COMMENT '横梁序列号';

ALTER TABLE `mo_uv_dispensing`
MODIFY COLUMN `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
MODIFY COLUMN `beam_sn` varchar(255) DEFAULT NULL COMMENT '横梁序列号',
MODIFY COLUMN `glue_width` float DEFAULT NULL COMMENT '胶宽',
MODIFY COLUMN `glue_width_usl` float DEFAULT NULL COMMENT '胶宽上限',
MODIFY COLUMN `circle_center_offset` float DEFAULT NULL COMMENT '圆心偏移',
MODIFY COLUMN `circle_center_offset_usl` float DEFAULT NULL COMMENT '圆心偏移上限',
MODIFY COLUMN `image_path` varchar(100) DEFAULT NULL COMMENT '图片路径',
MODIFY COLUMN `add_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
MODIFY COLUMN `error_code` int DEFAULT NULL COMMENT '错误代码',
MODIFY COLUMN `ng_reason` varchar(100) DEFAULT NULL COMMENT '不良原因',
MODIFY COLUMN `station_num` int DEFAULT NULL COMMENT '工位编号',
MODIFY COLUMN `side` enum('left','right','') DEFAULT NULL COMMENT '侧边',
MODIFY COLUMN `position` varchar(255) DEFAULT NULL COMMENT '位置',
MODIFY COLUMN `mo_process_step_production_result_id` bigint DEFAULT NULL COMMENT '生产结果ID',
MODIFY COLUMN `glue_width_lsl` float DEFAULT NULL COMMENT '胶宽下限',
MODIFY COLUMN `check_glue_weight` float DEFAULT NULL COMMENT '胶重';

ALTER TABLE `mo_dirty_check`
MODIFY COLUMN `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
MODIFY COLUMN `stain_size_usl` float DEFAULT NULL COMMENT '污渍尺寸上限',
MODIFY COLUMN `stain_count_usl` float DEFAULT NULL COMMENT '污渍数量上限',
MODIFY COLUMN `stains` varchar(255) DEFAULT NULL COMMENT '污渍描述',
MODIFY COLUMN `image_path` varchar(100) DEFAULT NULL COMMENT '图片路径',
MODIFY COLUMN `error_code` int DEFAULT NULL COMMENT '错误代码',
MODIFY COLUMN `beam_sn` varchar(255) DEFAULT NULL COMMENT '横梁序列号',
MODIFY COLUMN `ng_reason` varchar(100) DEFAULT NULL COMMENT '不良原因',
MODIFY COLUMN `add_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
MODIFY COLUMN `station_num` int DEFAULT NULL COMMENT '工位编号',
MODIFY COLUMN `side` enum('left','right','') DEFAULT NULL COMMENT '侧边',
MODIFY COLUMN `position` varchar(255) DEFAULT NULL COMMENT '位置',
MODIFY COLUMN `mo_process_step_production_result_id` bigint DEFAULT NULL COMMENT '生产结果ID',
MODIFY COLUMN `plasma_power_spec` float DEFAULT NULL COMMENT 'Plasma设定功率',
MODIFY COLUMN `lens_gripper_spec` float DEFAULT NULL COMMENT '镜头夹爪设定值';

ALTER TABLE `mo_auto_adjust_st08`
MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
MODIFY COLUMN `beam_sn` varchar(20) NOT NULL COMMENT '横梁SN',
MODIFY COLUMN `side` enum('left','right','') DEFAULT NULL COMMENT '左侧镜头或右侧镜头',
MODIFY COLUMN `add_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
MODIFY COLUMN `mtf_center_value` float(10,4) DEFAULT NULL COMMENT '中心MTF平均数值，实际测试值',
MODIFY COLUMN `mtf_center_lsl` float(10,4) DEFAULT NULL COMMENT '中心MTF规格下限',
MODIFY COLUMN `mtf_leftup_value` float(10,4) DEFAULT NULL COMMENT '左上MTF平均数值',
MODIFY COLUMN `mtf_leftup_lsl` float(10,4) DEFAULT NULL COMMENT '左上MTF规格下限',
MODIFY COLUMN `mtf_rightup_value` float(10,4) DEFAULT NULL COMMENT '右上MTF平均数值',
MODIFY COLUMN `mtf_rightup_lsl` float(10,4) DEFAULT NULL COMMENT '右上MTF规格下限',
MODIFY COLUMN `mtf_leftdown_value` float(10,4) DEFAULT NULL COMMENT '左下MTF平均数值',
MODIFY COLUMN `mtf_leftdown_lsl` float(10,4) DEFAULT NULL COMMENT '左下MTF规格下限',
MODIFY COLUMN `mtf_rightdown_value` float(10,4) DEFAULT NULL COMMENT '右下MTF平均数值',
MODIFY COLUMN `mtf_rightdown_lsl` float(10,4) DEFAULT NULL COMMENT '右下MTF规格下限',
MODIFY COLUMN `image_path` varchar(256) DEFAULT NULL COMMENT '图片路径',
MODIFY COLUMN `oc_x_offset` float DEFAULT NULL COMMENT 'OC X偏移',
MODIFY COLUMN `oc_x_offset_usl` float DEFAULT NULL COMMENT 'OC X偏移规格上限',
MODIFY COLUMN `oc_y_offset_usl` float DEFAULT NULL COMMENT 'OC Y偏移规格上限',
MODIFY COLUMN `oc_y_offset` float DEFAULT NULL COMMENT 'OC Y偏移',
MODIFY COLUMN `cod_x_offset` float DEFAULT NULL COMMENT 'COD X偏移',
MODIFY COLUMN `cod_y_offset` float DEFAULT NULL COMMENT 'COD Y偏移',
MODIFY COLUMN `cod_x_offset_usl` float DEFAULT NULL COMMENT 'COD X偏移规格上限',
MODIFY COLUMN `cod_y_offset_usl` float DEFAULT NULL COMMENT 'COD Y偏移规格上限',
MODIFY COLUMN `mtf_range_offset` float DEFAULT NULL COMMENT 'MTF范围偏移',
MODIFY COLUMN `mtf_range_offset_usl` float DEFAULT NULL COMMENT 'MTF范围偏移规格上限',
MODIFY COLUMN `mo_process_step_production_result_id` bigint DEFAULT NULL COMMENT '生产结果ID',
MODIFY COLUMN `position` varchar(255) DEFAULT NULL COMMENT '位置',
MODIFY COLUMN `stage` varchar(255) DEFAULT NULL COMMENT '阶段',
MODIFY COLUMN `aa_claw_grip_pressure` float DEFAULT NULL COMMENT 'AA夹爪握力',
MODIFY COLUMN `aa_claw_grip_pressure_spec` float DEFAULT NULL COMMENT 'AA夹爪握力规格',
MODIFY COLUMN `release_claw_minus_uv_cured_mtf_center_diff_usl` float DEFAULT NULL COMMENT '释放夹爪与UV固化MTF中心差规格上限',
MODIFY COLUMN `release_claw_minus_uv_cured_mtf_tl_diff_usl` float DEFAULT NULL COMMENT '释放夹爪与UV固化MTF左上差规格上限',
MODIFY COLUMN `release_claw_minus_uv_cured_mtf_tr_diff_usl` float DEFAULT NULL COMMENT '释放夹爪与UV固化MTF右上差规格上限',
MODIFY COLUMN `release_claw_minus_uv_cured_mtf_bl_diff_usl` float DEFAULT NULL COMMENT '释放夹爪与UV固化MTF左下差规格上限',
MODIFY COLUMN `release_claw_minus_uv_cured_mtf_br_diff_usl` float DEFAULT NULL COMMENT '释放夹爪与UV固化MTF右下差规格上限',
MODIFY COLUMN `error_code` int DEFAULT NULL COMMENT '错误代码',
MODIFY COLUMN `ng_reason` varchar(100) DEFAULT NULL COMMENT '不良原因',
MODIFY COLUMN `uv_exposure_time_spec` decimal(10,2) DEFAULT NULL COMMENT 'UV曝光时间规格',
MODIFY COLUMN `uv_energy_spec` decimal(10,2) DEFAULT NULL COMMENT 'UV能量规格',
MODIFY COLUMN `check_glue_weight_spec` decimal(10,3) DEFAULT NULL COMMENT '胶水重量规格',
MODIFY COLUMN `axis_movement_distance_spec` decimal(10,2) DEFAULT NULL COMMENT '轴移动距离规格',
MODIFY COLUMN `test_card_illuminance_spec` decimal(10,2) DEFAULT NULL COMMENT '测试卡照度规格',
MODIFY COLUMN `test_card_height_spec` decimal(10,2) DEFAULT NULL COMMENT '测试卡高度规格';