CREATE TABLE IF NOT EXISTS `mo_aa_final_comprehensive_inspection` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `current_consumption` decimal(10,4) DEFAULT NULL COMMENT '消费电流 (mA)',
  `frame_rate` decimal(10,2) DEFAULT NULL COMMENT '帧率 (fps)',
  `bad_pixels` int DEFAULT NULL COMMENT '坏点数量',
  `contamination_level` varchar(50) DEFAULT NULL COMMENT '脏污等级或描述',
  `clarity_score` decimal(10,2) DEFAULT NULL COMMENT '清晰度评分',
  `image_quality_color` varchar(50) DEFAULT NULL COMMENT '出图质量-色彩',
  `image_quality_gray` varchar(50) DEFAULT NULL COMMENT '出图质量-灰阶',
  `flare_level` varchar(50) DEFAULT NULL COMMENT 'Flare（炫光）等级或描述',
  `oc_x_offset` decimal(10,4) DEFAULT NULL COMMENT 'OC X偏差值 (mm)',
  `oc_y_offset` decimal(10,4) DEFAULT NULL COMMENT 'OC Y偏差值 (mm)',
  `mo_process_step_production_result_id` bigint DEFAULT NULL,
  `error_code` int DEFAULT NULL,
  `station_num` int DEFAULT NULL,
  `ng_reason` varchar(100) DEFAULT NULL,
  `add_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `beam_sn` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='综合检测记录表';

CREATE TABLE IF NOT EXISTS `mo_beam_appearance_inspection` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `aa_hole_diameter` decimal(10,4) DEFAULT NULL COMMENT 'AA孔直径',
  `aa_hole_distance` decimal(10,4) DEFAULT NULL COMMENT 'AA孔两孔孔距',
  `aa_hole_center_x` decimal(10,4) DEFAULT NULL COMMENT 'AA孔中心X值',
  `aa_hole_center_y` decimal(10,4) DEFAULT NULL COMMENT 'AA孔中心Y值',
  `thread_hole_distance` decimal(10,4) DEFAULT NULL COMMENT '螺纹孔四孔孔距',
  `thread_hole_center_x` decimal(10,4) DEFAULT NULL COMMENT '螺纹孔中心X值',
  `thread_hole_center_y` decimal(10,4) DEFAULT NULL COMMENT '螺纹孔中心Y值',
  `surface_height_diff` decimal(10,4) DEFAULT NULL COMMENT '两贴合面高度差',
  `surface_to_beam_diff` decimal(10,4) DEFAULT NULL COMMENT '贴合面与横梁基准面差值',
  `beam_length` decimal(10,4) DEFAULT NULL COMMENT '横梁整体长度',
  `beam_width` decimal(10,4) DEFAULT NULL COMMENT '横梁整体宽度',
  `mo_process_step_production_result_id` bigint DEFAULT NULL,
  `error_code` int DEFAULT NULL,
  `station_num` int DEFAULT NULL,
  `ng_reason` varchar(100) DEFAULT NULL,
  `add_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `beam_sn` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='横梁外观检测数据';

CREATE TABLE IF NOT EXISTS `mo_cmos_appearance_inspection` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `sensor_parallelism` decimal(10,4) DEFAULT NULL COMMENT 'Sensor 平行度',
  `hole_distance` decimal(10,4) DEFAULT NULL COMMENT '两孔间距',
  `mo_process_step_production_result_id` bigint DEFAULT NULL,
  `error_code` int DEFAULT NULL,
  `station_num` int DEFAULT NULL,
  `ng_reason` varchar(100) DEFAULT NULL,
  `add_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `beam_sn` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='CMOS 外观检测数据' ;

CREATE TABLE IF NOT EXISTS `mo_device_status` (
  `id` int NOT NULL AUTO_INCREMENT,
  `product_material_no` varchar(255) DEFAULT NULL,
  `device_no` varchar(255) DEFAULT NULL,
  `others` json DEFAULT NULL,
  `add_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `production_count` int DEFAULT NULL,
  `defect_count` int DEFAULT NULL,
  `uph` int DEFAULT NULL,
  `oee` float DEFAULT NULL,
  `status` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=168 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `mo_high_temp_curing_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tray_no` varchar(50) NOT NULL COMMENT '料盘号',
  `oven_no` varchar(50) NOT NULL COMMENT '炉号',
  `min_temp` decimal(6,2) DEFAULT NULL COMMENT '最低炉温 (°C)',
  `max_temp` decimal(6,2) DEFAULT NULL COMMENT '最高炉温 (°C)',
  `bake_duration_minutes` int DEFAULT NULL COMMENT '烘烤时间（分钟）',
  `mo_process_step_production_result_id` bigint DEFAULT NULL,
  `error_code` int DEFAULT NULL,
  `station_num` int DEFAULT NULL,
  `ng_reason` varchar(100) DEFAULT NULL,
  `add_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `beam_sn` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='高温固化工序记录表';

CREATE TABLE IF NOT EXISTS `mo_screw_tightening_inspection` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `torque` decimal(10,4) DEFAULT NULL COMMENT '扭力 (N·m)',
  `angle` decimal(10,2) DEFAULT NULL COMMENT '角度 (°)',
  `turns` decimal(10,2) DEFAULT NULL COMMENT '圈数',
  `screw_height` decimal(10,4) DEFAULT NULL COMMENT '锁付高度 (mm)',
  `mo_process_step_production_result_id` bigint DEFAULT NULL,
  `error_code` int DEFAULT NULL,
  `station_num` int DEFAULT NULL,
  `ng_reason` varchar(100) DEFAULT NULL,
  `add_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `beam_sn` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='锁付检测数据';

CREATE TABLE IF NOT EXISTS `calibresult` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `CameraSN` varchar(24) DEFAULT NULL,
  `TimeStamp` varchar(24) DEFAULT NULL,
  `LeftSharpness` float(10,6) DEFAULT NULL,
  `RightSharpness` float(10,6) DEFAULT NULL,
  `Simor_validPattern` float(10,6) DEFAULT NULL,
  `Simor_mean_reprojection_error` float(10,6) DEFAULT NULL,
  `Simor_mean_left_reprojection_error` float(10,6) DEFAULT NULL,
  `Simor_mean_right_reprojection_error` float(10,6) DEFAULT NULL,
  `Simor_max_left_reprojection_error` float(10,6) DEFAULT NULL,
  `Simor_max_right_reprojection_error` float(10,6) DEFAULT NULL,
  `Simor_amplify_ratio` float(10,6) DEFAULT NULL,
  `Simor_left_trim` float(10,6) DEFAULT NULL,
  `Simor_right_trim` float(10,6) DEFAULT NULL,
  `Simor_fov_h` float(10,6) DEFAULT NULL,
  `Simor_fov_v` float(10,6) DEFAULT NULL,
  `Simor_simor_calc_result` float(10,6) DEFAULT NULL,
  `ISP_validPattern` float(10,6) DEFAULT NULL,
  `ISP_mean_reprojection_error` float(10,6) DEFAULT NULL,
  `ISP_mean_left_reprojection_error` float(10,6) DEFAULT NULL,
  `ISP_mean_right_reprojection_error` float(10,6) DEFAULT NULL,
  `ISP_max_left_reprojection_error` float(10,6) DEFAULT NULL,
  `ISP_max_right_reprojection_error` float(10,6) DEFAULT NULL,
  `ISP_amplify_ratio` float(10,6) DEFAULT NULL,
  `ISP_left_trim` float(10,6) DEFAULT NULL,
  `ISP_right_trim` float(10,6) DEFAULT NULL,
  `ISP_fov_h` float(10,6) DEFAULT NULL,
  `ISP_fov_v` float(10,6) DEFAULT NULL,
  `ISP_simor_calc_result` float(10,6) DEFAULT NULL,
  `ISP_RectifyVerticalOffset` float(10,6) DEFAULT NULL,
  `Simor_left_fx` float(10,6) DEFAULT NULL,
  `Simor_left_fy` float(10,6) DEFAULT NULL,
  `Simor_left_cx` float(10,6) DEFAULT NULL,
  `Simor_left_cy` float(10,6) DEFAULT NULL,
  `Simor_left_k1` float(10,6) DEFAULT NULL,
  `Simor_left_k2` float(10,6) DEFAULT NULL,
  `Simor_left_k3` float(10,6) DEFAULT NULL,
  `Simor_left_p1` float(10,6) DEFAULT NULL,
  `Simor_left_p2` float(10,6) DEFAULT NULL,
  `Simor_right_fx` float(10,6) DEFAULT NULL,
  `Simor_right_fy` float(10,6) DEFAULT NULL,
  `Simor_right_cx` float(10,6) DEFAULT NULL,
  `Simor_right_cy` float(10,6) DEFAULT NULL,
  `Simor_right_k1` float(10,6) DEFAULT NULL,
  `Simor_right_k2` float(10,6) DEFAULT NULL,
  `Simor_right_k3` float(10,6) DEFAULT NULL,
  `Simor_right_p1` float(10,6) DEFAULT NULL,
  `Simor_right_p2` float(10,6) DEFAULT NULL,
  `Simor_width` float(10,6) DEFAULT NULL,
  `Simor_height` float(10,6) DEFAULT NULL,
  `Simor_bxf` float(12,6) DEFAULT NULL,
  `Simor_baseline` float(10,6) DEFAULT NULL,
  `Simor_focus` float(10,6) DEFAULT NULL,
  `Simor_cx` float(10,6) DEFAULT NULL,
  `Simor_cy` float(10,6) DEFAULT NULL,
  `Simor_out_width` float(10,6) DEFAULT NULL,
  `Simor_out_height` float(10,6) DEFAULT NULL,
  `Simor_r0` float(10,6) DEFAULT NULL,
  `Simor_r1` float(10,6) DEFAULT NULL,
  `Simor_r2` float(10,6) DEFAULT NULL,
  `Simor_t0` float(10,6) DEFAULT NULL,
  `Simor_t1` float(10,6) DEFAULT NULL,
  `Simor_t2` float(10,6) DEFAULT NULL,
  `Simor_left_r0` float(10,6) DEFAULT NULL,
  `Simor_left_r1` float(10,6) DEFAULT NULL,
  `Simor_left_r2` float(10,6) DEFAULT NULL,
  `Simor_right_r0` float(10,6) DEFAULT NULL,
  `Simor_right_r1` float(10,6) DEFAULT NULL,
  `Simor_right_r2` float(10,6) DEFAULT NULL,
  `Simor_virtual_width` float(10,6) DEFAULT NULL,
  `Simor_virtual_height` float(10,6) DEFAULT NULL,
  `Simor_ROI_X` float(10,6) DEFAULT NULL,
  `Simor_ROI_Y` float(10,6) DEFAULT NULL,
  `ISP_left_fx` float(10,6) DEFAULT NULL,
  `ISP_left_fy` float(10,6) DEFAULT NULL,
  `ISP_left_cx` float(10,6) DEFAULT NULL,
  `ISP_left_cy` float(10,6) DEFAULT NULL,
  `ISP_left_k1` float(10,6) DEFAULT NULL,
  `ISP_left_k2` float(10,6) DEFAULT NULL,
  `ISP_left_k3` float(10,6) DEFAULT NULL,
  `ISP_left_p1` float(10,6) DEFAULT NULL,
  `ISP_left_p2` float(10,6) DEFAULT NULL,
  `ISP_right_fx` float(10,6) DEFAULT NULL,
  `ISP_right_fy` float(10,6) DEFAULT NULL,
  `ISP_right_cx` float(10,6) DEFAULT NULL,
  `ISP_right_cy` float(10,6) DEFAULT NULL,
  `ISP_right_k1` float(10,6) DEFAULT NULL,
  `ISP_right_k2` float(10,6) DEFAULT NULL,
  `ISP_right_k3` float(10,6) DEFAULT NULL,
  `ISP_right_p1` float(10,6) DEFAULT NULL,
  `ISP_right_p2` float(10,6) DEFAULT NULL,
  `ISP_width` float(10,6) DEFAULT NULL,
  `ISP_height` float(10,6) DEFAULT NULL,
  `ISP_bxf` float(12,6) DEFAULT NULL,
  `ISP_baseline` float(10,6) DEFAULT NULL,
  `ISP_focus` float(10,6) DEFAULT NULL,
  `ISP_cx` float(10,6) DEFAULT NULL,
  `ISP_cy` float(10,6) DEFAULT NULL,
  `ISP_out_width` float(10,6) DEFAULT NULL,
  `ISP_out_height` float(10,6) DEFAULT NULL,
  `ISP_r0` float(10,6) DEFAULT NULL,
  `ISP_r1` float(10,6) DEFAULT NULL,
  `ISP_r2` float(10,6) DEFAULT NULL,
  `ISP_t0` float(10,6) DEFAULT NULL,
  `ISP_t1` float(10,6) DEFAULT NULL,
  `ISP_t2` float(10,6) DEFAULT NULL,
  `ISP_left_r0` float(10,6) DEFAULT NULL,
  `ISP_left_r1` float(10,6) DEFAULT NULL,
  `ISP_left_r2` float(10,6) DEFAULT NULL,
  `ISP_right_r0` float(10,6) DEFAULT NULL,
  `ISP_right_r1` float(10,6) DEFAULT NULL,
  `ISP_right_r2` float(10,6) DEFAULT NULL,
  `ISP_virtual_width` float(10,6) DEFAULT NULL,
  `ISP_virtual_height` float(10,6) DEFAULT NULL,
  `ISP_ROI_X` float(10,6) DEFAULT NULL,
  `ISP_ROI_Y` float(10,6) DEFAULT NULL,
  `Simor_Ref_fx` float(10,6) DEFAULT NULL,
  `Simor_Ref_fy` float(10,6) DEFAULT NULL,
  `Simor_Ref_cx` float(10,6) DEFAULT NULL,
  `Simor_Ref_cy` float(10,6) DEFAULT NULL,
  `Simor_Ref_k1` float(10,6) DEFAULT NULL,
  `Simor_Ref_k2` float(10,6) DEFAULT NULL,
  `Simor_Ref_k3` float(10,6) DEFAULT NULL,
  `Simor_Ref_p1` float(10,6) DEFAULT NULL,
  `Simor_Ref_p2` float(10,6) DEFAULT NULL,
  `Simor_Ref_width` float(10,6) DEFAULT NULL,
  `Simor_Ref_height` float(10,6) DEFAULT NULL,
  `LeftCenterOffsetX` int DEFAULT NULL,
  `LeftCenterOffsetY` int DEFAULT NULL,
  `RightCenterOffsetX` int DEFAULT NULL,
  `RightCenterOffsetY` int DEFAULT NULL,
  `Station` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=127686 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `mo_calibration` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `camera_sn` varchar(16) NOT NULL,
  `station_number` int NOT NULL COMMENT '工位号',
  `operator` varchar(64) NOT NULL COMMENT '操作人员',
  `start_time` datetime NOT NULL COMMENT '工序开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '工序结束时间',
  `sharpness_left` float(10,4) DEFAULT NULL COMMENT '左清晰度',
  `sharpness_right` float(10,4) DEFAULT NULL COMMENT '右清晰度',
  `left_trim` int DEFAULT NULL COMMENT '左镜头裁剪行数',
  `right_trim` int DEFAULT NULL COMMENT '右镜头裁剪行数',
  `validPattern` int DEFAULT NULL COMMENT '有效图像张数',
  `meanReprojectionError` float(10,6) DEFAULT NULL COMMENT '平 左右相机均逆投影误差',
  `meanLeftReprojectionError` float(10,6) DEFAULT NULL COMMENT '左相机平均逆投影误差',
  `meanRightReprojectionError` float(10,6) DEFAULT NULL COMMENT '右相机平均逆投影误差',
  `maxLeftReprojectionError` float(10,6) DEFAULT NULL COMMENT '左相机最大逆投影误差',
  `maxRightReprojectionError` float(10,6) DEFAULT NULL COMMENT '右相机最大逆投影误差',
  `img_yml2data_fov` float(4,1) DEFAULT NULL COMMENT '原图的yml2data',
  `isp_yml2data_fov` float(4,1) DEFAULT NULL COMMENT 'isp的yml2data',
  `epr_filename` varchar(256) DEFAULT NULL COMMENT 'epr文件（路径+名称）',
  `yml_filename` varchar(256) DEFAULT NULL COMMENT 'yml文件（路径+名称）',
  `isp_line_offset` float(10,4) DEFAULT NULL COMMENT 'isp行差',
  `file_path` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '标定文件存储路径',
  `error_code` int DEFAULT NULL COMMENT '错误码',
  `tool_version` varchar(255) DEFAULT NULL,
  `self_check_errcode` bigint DEFAULT NULL,
  `self_check_error_desc` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_Reference_11` (`operator`),
  KEY `Index_3` (`start_time`),
  CONSTRAINT `FK_Reference_11` FOREIGN KEY (`operator`) REFERENCES `mo_user_info` (`user_name`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=131934 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='标定工具数据表';

